package document

type Document struct {
	Type     Types
	ID       string
	Filename string
	Package  string
	Globals  map[string]Types
}

func NewDocument(ctx *DocumentContext, id string, anonymousStruct Types, filename string) *Document {
	return &Document{
		anonymousStruct,
		id,
		filename,
		ctx.Package,
		ctx.Globals,
	}

}

const DocumentTemplate = `
// Code generated by jsonschema. DO NOT EDIT.

{{- if .Package}}
package {{.Package}}
{{else}}
package main
{{- end}}

{{ if .ID -}}
// ID: {{.ID}}
{{ end }}

{{ if .Type -}}
	{{template "kind" .Type }}
{{end -}}


{{range $key, $global := .Globals -}}
	{{- template "kind" $global -}}
{{end}}
`
