// Code generated by jsonschema. DO NOT EDIT.
package main

// JSON Schema for an fstab entry
// ID: http://example.com/entry-schema
type EntrySchema struct {
	Storage interface{} `json:"Storage"`
}

// DiskDevice
// ID: #/definitions/diskDevice
type DiskDevice struct {
}

func (s *DiskDevice) storage() {}

// DiskUUID
// ID: #/definitions/diskUUID
type DiskUUID struct {
}

func (s *DiskUUID) storage() {}

// Nfs
// ID: #/definitions/nfs
type Nfs struct {
}

func (s *Nfs) storage() {}

// Tmpfs
// ID: #/definitions/tmpfs
type Tmpfs struct {
}

func (s *Tmpfs) storage() {}
