// Code generated by jsonschema. DO NOT EDIT.
package main

// JSON Schema for an fstab entry
// ID: http://example.com/entry-schema
type entrySchema struct {
	Storage Storage `json:"Storage,omitempty", validate:"required"`
}

// Storage
// #/definitions/diskDevice
// #/definitions/diskUUID
// #/definitions/nfs
// #/definitions/tmpfs
type Storage interface {
	storage()
}

type DiskDevice struct {
}

func (s *DiskDevice) storage() {}

type DiskUUID struct {
}

func (s *DiskUUID) storage() {}

type Nfs struct {
}

func (s *Nfs) storage() {}

type Tmpfs struct {
}

func (s *Tmpfs) storage() {}
