// Code generated by jsonschema. DO NOT EDIT.
package main

// ID: https://example.com/geographical-location.schema.json

// A geographical coordinate on a planet (most commonly Earth).
type GeographicalLocation struct {
	Latitude  float64 `json:"Latitude" validate:"gte=-90,lte=90,required"`
	Longitude float64 `json:"Longitude" validate:"gte=-180,lte=180,required"`
}
