// Code generated by jsonschema. DO NOT EDIT.
package main

// A geographical coordinate on a planet (most commonly Earth).
// ID: https://example.com/geographical-location.schema.json
type GeographicalLocationSchemaJson struct {
	Longitude *float64 `json:"longitude,omitempty", validate:"required,lte=180,gte=-180"`
	Latitude  *float64 `json:"latitude,omitempty", validate:"required,lte=90,gte=-90"`
}
