// Code generated by jsonschema. DO NOT EDIT.
package main

// personSchema
// ID: https://example.com/person.schema.json
type personSchema struct {
	// The person's first name.
	FirstName string `json:"FirstName"`
	// The person's last name.
	LastName string `json:"LastName"`
	// Age in years which must be equal to or greater than zero.
	Age int32 `json:"Age", validate:"gte=0"`
}
