// Code generated by jsonschema. DO NOT EDIT.
package main

// PersonSchema
// ID: https://example.com/person.schema.json
type PersonSchema struct {
	// The person's first name.
	FirstName string `json:"firstName"`
	// The person's last name.
	LastName string `json:"lastName"`
	// Age in years which must be equal to or greater than zero.
	Age int32 `json:"age", validate:"gte=0"`
}
