// Code generated by jsonschema. DO NOT EDIT.
package main

// A product from Acme's catalog
// ID: http://example.com/product.nesting.schema.json
type productNestingSchema struct {
	// The unique identifier for a product
	ProductId int32 `json:"ProductId"`
	// Name of the product
	ProductName string `json:"ProductName"`
	// The price of the product
	Price *float64 `json:"Price,omitempty", validate:"required,gt=0"`
	// Tags for the product
	Tags       []string `json:"Tags"`
	Dimensions struct {
		Length *float64 `json:"Length,omitempty", validate:"required"`
		Width  *float64 `json:"Width,omitempty", validate:"required"`
		Height *float64 `json:"Height,omitempty", validate:"required"`
	}
}
