// Code generated by jsonschema. DO NOT EDIT.
package main

// A product from Acme's catalog
// ID: http://example.com/product.schema.json
type productSchema struct {
	// Tags for the product
	Tags       []string `json:"Tags"`
	Dimensions struct {
		// length
		Length *float64 `json:"Length,omitempty", validate:"required"`
		Width  *float64 `json:"Width,omitempty", validate:"required"`
		Height *float64 `json:"Height,omitempty", validate:"required"`
	}

	WarehouseLocation struct {
		Latitude  *float64 `json:"omitempty,Latitude", validate:"required,lte=90,gte=-90"`
		Longitude *float64 `json:"Longitude,omitempty", validate:"required,lte=180,gte=-180"`
	}

	// The unique identifier for a product
	ProductId int32 `json:"ProductId"`
	// Name of the product
	ProductName string `json:"ProductName"`
	// The price of the product
	Price *float64 `json:"Price,omitempty", validate:"required,gt=0"`
}
