// Code generated by jsonschema. DO NOT EDIT.
package main

// A product from Acme's catalog
// ID: productNesting
type Product struct {
	// Name of the product
	ProductName string `json:"omitempty,productName", validate:"required"`
	// The price of the product
	Price *float64 `json:"price,omitempty", validate:"required,gt=0"`
	// Tags for the product
	Tags       []string `json:"tags"`
	Dimensions struct {
		Width  *float64 `json:"width,omitempty", validate:"required"`
		Height *float64 `json:"height,omitempty", validate:"required"`
		Length *float64 `json:"length,omitempty", validate:"required"`
	} `json:"Dimensions"`

	// The unique identifier for a product
	ProductId *int32 `json:"productId,omitempty", validate:"required"`
}
