// Code generated by jsonschema. DO NOT EDIT.
package main

// A product from Acme's catalog
// ID: http://example.com/product.schema.json
type ProductSchemaJson struct {
	Dimensions struct {
		// length
		Length *float64 `json:"length,omitempty", validate:"required"`
		Width  *float64 `json:"width,omitempty", validate:"required"`
		Height *float64 `json:"height,omitempty", validate:"required"`
	} `json:"Dimensions"`

	GeographicalLocationSchemaJson struct {
		Latitude  *float64 `json:"latitude,omitempty", validate:"gte=-90,required,lte=90"`
		Longitude *float64 `json:"longitude,omitempty", validate:"required,lte=180,gte=-180"`
	} `json:"GeographicalLocationSchemaJson"`

	// The unique identifier for a product
	ProductId *int32 `json:"productId,omitempty", validate:"required"`
	// Name of the product
	ProductName string `json:"productName,omitempty", validate:"required"`
	// The price of the product
	Price *float64 `json:"price,omitempty", validate:"gt=0,required"`
	// Tags for the product
	Tags []string `json:"tags"`
}
