// Code generated by jsonschema. DO NOT EDIT.
package main

// ID: id

// A product from Acme's catalog
type Product struct {
	Dimensions struct {
		Height float64 `json:"Height" validate:"required"`
		Length float64 `json:"Length" validate:"required"`
		Width  float64 `json:"Width" validate:"required"`
	} `json:"Dimensions,omitempty"`
	// The price of the product
	Price float64 `json:"Price" validate:"gt=0,required"`
	// The unique identifier for a product
	ProductId int32 `json:"ProductId" validate:"required"`
	// Name of the product
	ProductName string `json:"ProductName,omitempty" validate:"required"`
	// Tags for the product
	Tags []string `json:"Tags,omitempty"`
}
