// Code generated by jsonschema. DO NOT EDIT.
package main

// ID: http://example.com/product.schema.json

// A product from Acme's catalog
type Product struct {
	// The unique identifier for a product
	ProductId *int32 `json:"productId,omitempty", validate:"required"`
	// Name of the product
	ProductName string `json:"productName,omitempty", validate:"required"`
	// The price of the product
	Price *float64 `json:"price,omitempty", validate:"required,gt=0"`
	// Tags for the product
	Tags []string `json:"tags"`
	string
	Dimensions struct {
		Length *float64 `json:"length,omitempty", validate:"required"`
		Width  *float64 `json:"width,omitempty", validate:"required"`
		Height *float64 `json:"height,omitempty", validate:"required"`
	} `json:"Dimensions"`
}
