// Code generated by jsonschema. DO NOT EDIT.
package main

// Storage
// #/definitions/diskDevice
// #/definitions/diskUUID
// #/definitions/nfs
// #/definitions/tmpfs
type Storage interface {
	storage()
}
