// Code generated by jsonschema. DO NOT EDIT.
package referenceOutside

// ID: http://example.com/reference-outside.json

// A product from Acme's catalog
type Product struct {
	// Tags for the product
	Tags       []string `json:"tags,omitempty"`
	Dimensions struct {
		// length
		Length float64 `json:"length", validate:"required"`
		Width  float64 `json:"width", validate:"required"`
		Height float64 `json:"height", validate:"required"`
	} `json:"dimensions,omitempty"`

	// Coordinates of the warehouse where the product is located.
	WarehouseLocation Location `json:"warehouseLocation,omitempty"`
	// The unique identifier for a product
	ProductId *int32 `json:"productId,omitempty"`
	// Name of the product
	ProductName *string `json:"productName,omitempty"`
	// The price of the product
	Price float64 `json:"price", validate:"required,gt=0"`
}
