// Code generated by jsonschema. DO NOT EDIT.
package referenceOutside

// ID: https://example.com/reference-outside.schema.json

// A geographical coordinate on a planet (most commonly Earth).
type Location struct {
	Latitude  *float64 `json:"latitude,omitempty", validate:"gte=-90,lte=90"`
	Longitude *float64 `json:"longitude,omitempty", validate:"lte=180,gte=-180"`
}
