// Code generated by jsonschema. DO NOT EDIT.
package allOfObject

// ID: http://example.com/allof.json

type Allof struct {
	Storage AllofStorage `json:"storage", validate:"required,allof"`
}

type AllofStorage struct {
	Speed  *float64 `json:"speed,omitempty"`
	Name   *string  `json:"name,omitempty"`
	Amount *float64 `json:"amount,omitempty"`
}

type Test2 struct {
	Amount *float64 `json:"amount,omitempty"`
}
