// Code generated by jsonschema. DO NOT EDIT.
package allOf

// ID: http://example.com/allof.json

type Allof struct {
	Storage *AllofStorage `json:"storage,omitempty", validate:"allof"`
}

type AllofStorage struct {
	Speed *float64 `json:"speed,omitempty"`
	Test2 Test2    `json:"test2,omitempty"`
	Name  *string  `json:"name,omitempty"`
}

type Test2 string
