// Code generated by jsonschema. DO NOT EDIT.
package enum

// ID: https://example.com/enum.json

type Length string

const (
	Length_Meters Length = "meters"
	Length_Feet   Length = "feet"
)

type KeyType string

const (
	KeyType_Red   KeyType = "red"
	KeyType_Amber KeyType = "amber"
	KeyType_Green KeyType = "green"
)
