// Code generated by jsonschema. DO NOT EDIT.
package reference

// ID: https://example.com/reference.json

type Address struct {
	State         string `json:"state", validate:"required"`
	StreetAddress string `json:"street_address", validate:"required"`
	City          string `json:"city", validate:"required"`
}

type HomeAddress Address
