// Code generated by jsonschema. DO NOT EDIT.
package oneOf

import "encoding/json"

// ID: http://example.com/oneof.json

// JSON Schema for an fstab entry
type DiskDevice struct {
}

func (s *DiskDevice) oneofStorage() {}

// JSON Schema for an fstab entry
type DiskUUID struct {
}

func (s *DiskUUID) oneofStorage() {}

// JSON Schema for an fstab entry
type Nfs struct {
}

func (s *Nfs) oneofStorage() {}

// JSON Schema for an fstab entry
type Oneof struct {
	OneofStorage OneofStorage `json:"storage,omitempty", validate:"oneof"`
}

func (s *Oneof) unmarshalJSON(b []byte) error {
	m := map[string]json.RawMessage{}
	if err := json.Unmarshal(b, &m); err != nil {
		return nil
	}

	oneofStorage := func() OneofStorage {
		raw, ok := m["oneof storage"]
		if !ok {
			return nil
		}

		var oneofStorage0 OneofStorage0
		if err := json.Unmarshal(raw, &oneofStorage0); err == nil {
			return &oneofStorage0
		}

		var diskDevice DiskDevice
		if err := json.Unmarshal(raw, &diskDevice); err == nil {
			return &diskDevice
		}

		var diskUUID DiskUUID
		if err := json.Unmarshal(raw, &diskUUID); err == nil {
			return &diskUUID
		}

		var nfs Nfs
		if err := json.Unmarshal(raw, &nfs); err == nil {
			return &nfs
		}

		var tmpfs Tmpfs
		if err := json.Unmarshal(raw, &tmpfs); err == nil {
			return &tmpfs
		}

		return nil
	}
	type Alias Oneof
	aux := &struct {
		OneofStorage OneofStorage `json:"storage,omitempty", validate:"oneof"`
		*Alias
	}{
		OneofStorage: oneofStorage(),
		Alias:        (*Alias)(s),
	}

	s.OneofStorage = aux.OneofStorage

	return nil
}

// OneofStorage
type OneofStorage interface {
	oneofStorage()
}
type OneofStorage0 struct {
	Name  *string  `json:"name,omitempty"`
	Speed *float64 `json:"speed,omitempty"`
}

func (s *OneofStorage0) oneofStorage() {}

// JSON Schema for an fstab entry
type Tmpfs struct {
}

func (s *Tmpfs) oneofStorage() {}
