package parser

type Document struct {
	*Type
	ID       string
	Filename string
	Package  string
	Globals  map[string]Types
}

func NewDocument(ctx *SchemaContext, id string, anonymousStruct Types, filename string) *Document {
	s := PrefixType(anonymousStruct)
	return &Document{
		s,
		id,
		filename,
		ctx.Package,
		ctx.Globals,
	}

}

const DocumentTemplate = `
// Code generated by jsonschema. DO NOT EDIT.

{{- if .Package}}
package {{.Package}}
{{else}}
package main
{{- end}}

{{ if .ID -}}
// ID: {{.ID}}
{{ end }}

{{ if .Type -}}
	{{template "type" .Type }}
{{end -}}


{{range $key, $global := .Globals -}}
	{{- template "kind" $global -}}
{{end}}
`
