package parser

type Struct struct {
	*AnonymousStruct
	Package     string

}

func NewStruct(ctx *SchemaContext, anonymousStruct *AnonymousStruct) *Struct {
	return &Struct{
		anonymousStruct,
		ctx.Package,
	}

}

const StructTemplate = `
// Code generated by jsonschema. DO NOT EDIT.

{{- if .Package}}
package {{.Package}}
{{else}}
package main
{{- end}}



{{if .Comment -}}
// {{ .Comment}}
{{ else -}}
// {{ .Name}}
{{end -}}
{{ if .ID -}}
// ID: {{.ID}}
{{ end -}}
type {{template "struct" .AnonymousStruct }}

{{range $key, $definition := .AnonymousStruct.Definitions -}}
	{{if $definition.Comment -}}
	// {{ $definition.Comment}}
	{{ else }}
	// {{$definition.Name}}
	{{end -}}
	{{if $definition.ID -}}
	// ID: {{ $definition.ID}}
	{{end -}}
	type {{template "struct" $definition }}
{{ end -}}
`