package parser

type Struct struct {
	*AnonymousStruct
	Filename string
	Package     string

}

func NewStruct(ctx *SchemaContext, anonymousStruct *AnonymousStruct, filename string) *Struct {
	return &Struct{
		anonymousStruct,
		filename,
		ctx.Package,
	}

}

const StructTemplate = `
// Code generated by jsonschema. DO NOT EDIT.

{{- if .Package}}
package {{.Package}}
{{else}}
package main
{{- end}}



{{if .Comment -}}
// {{ .Comment}}
{{ else -}}
// {{ .Name}}
{{end -}}
{{ if .ID -}}
// ID: {{.ID}}
{{ end -}}
type {{template "struct" .AnonymousStruct }}


`