package parser

type Struct struct {
	*AnonymousStruct
	Definitions []*Definition
	Filename string
	Package     string

}

func NewStruct(ctx *SchemaContext, anonymousStruct *AnonymousStruct, definitions []*Definition, filename string) *Struct {
	return &Struct{
		anonymousStruct,
		definitions,
		filename,
		ctx.Package,
	}

}

const StructTemplate = `
// Code generated by jsonschema. DO NOT EDIT.

{{- if .Package}}
package {{.Package}}
{{else}}
package main
{{- end}}

{{if .Comment -}}
// {{ .Comment}}
{{ else -}}
	{{ if .Name}}// {{ .Name}}{{ end }}
{{end -}}
{{ if .ID -}}
// ID: {{.ID}}
{{ end -}}
{{ if .AnonymousStruct -}}
	{{ if .AnonymousStruct.IsNotEmpty -}}
		type {{template "struct" .AnonymousStruct }}
	{{ end -}}
{{end -}}
{{range $key, $definition := .Definitions -}}
type {{template "struct" $definition }}
{{end -}}
`