// Code generated by jsonschema. DO NOT EDIT.
package nesting

// ID: http://example.com/nesting.json

// A product from Acme's catalog
type Product struct {
	// Name of the product
	ProductName *string `json:"productName,omitempty"`
	// The price of the product
	Price *float64 `json:"price,omitempty", validate:"gt=0"`
	// Tags for the product
	Tags       []string `json:"tags,omitempty"`
	Dimensions *struct {
		Height float64 `json:"height", validate:"required"`
		Length float64 `json:"length", validate:"required"`
		Width  float64 `json:"width", validate:"required"`
	} `json:"dimensions,omitempty"`

	ProductType *ProductType `json:"type,omitempty"`
	// The unique identifier for a product
	ProductId *int32 `json:"productId,omitempty"`
}

type ProductType string

const (
	ProductType_Red   ProductType = "red"
	ProductType_Amber ProductType = "amber"
	ProductType_Green ProductType = "green"
)
