// Code generated by jsonschema. DO NOT EDIT.
package anyOf

import "encoding/json"

// ID: http://example.com/anyof.json

type Anyof struct {
	Storage []Storage `json:"storage,omitempty", validate:"anyof"`
}

func (s *Anyof) unmarshalJSON(b []byte) error {
	m := map[string]json.RawMessage{}
	if err := json.Unmarshal(b, &m); err != nil {
		return nil
	}

	storage := func() []Storage {
		var storage []Storage
		raw, ok := m["storage"]
		if !ok {
			return storage
		}

		var array []json.RawMessage
		if err := json.Unmarshal(raw, &array); err != nil {
			return storage
		}

		for _, item := range array {
			var test *Test
			if err := json.Unmarshal(item, &test); err == nil {
				storage = append(storage, test)
			}

			var storage1 *Storage1
			if err := json.Unmarshal(item, &storage1); err == nil {
				storage = append(storage, storage1)
			}
		}

		return storage
	}
	type Alias Anyof
	aux := &struct {
		Storage []Storage `json:"storage,omitempty", validate:"anyof"`
		*Alias
	}{
		Storage: storage(),
		Alias:   (*Alias)(s),
	}

	s.Storage = aux.Storage

	return nil
}

// Storage
type Storage interface {
	storage()
}
type Storage1 float64

func (s *Storage1) storage() {}

type Test string

func (s *Test) storage() {}
